
```{r, include=FALSE}
library(tidyverse)
library(magrittr)
library(readr)
library(feather)
library(usmap)
```

```{r}
nchs <- read_feather("./nchs.feather")
```

```{r}
#counties with no population
nchs[is.na(nchs$popul), ]
```

```{r}
plot_usmap(data = nchs, values = "nchs") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) 
```

```{r}
county_train <- read_feather("./county_train.feather")
```

```{r}
## distribution of nchs in county_train
train_fips <- unique(county_train$fips)

summary(nchs$nchs)
summary(nchs$nchs[nchs$fips %in% train_fips])
```

```{r}
plot_usmap(data = nchs, include = unique(train_fips), 
           values = "nchs") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) 
```

```{r}
source("./county_features.R")
```

```{r}
# why are counties having an nchs of 1,2,3,4 not in county_train?
nchs %>% 
  select(nchs, cbsa, county, fips) %>% 
  filter(nchs %in% c(1,2,3,4), 
         !fips %in% train_fips) %>% 
  arrange(nchs) %>% 
  left_join(filter(county_features, index_desc == 1))
```
